services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_storage
    ports:
      - "5442:5432"
    networks:
      - application-network
    volumes:
      - postgres-data:/data
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - application-network
    volumes:
      - minio-data:/data
    command:
      server /data --console-address ":9001"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud_storage
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: password

      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: password
      MINIO_BUCKET: user-files

      SERVER_PORT: 8090
    ports:
      - "8090:8090"
    networks:
      - application-network


networks:
  application-network:
    name: application-network
    driver: bridge

volumes:
  postgres-data:
  minio-data: